title: Settings
data:
  site_name: 'Tony''s Personal Home Page'
  social:
    -
      name: Twitter
      url: 'https://twitter.com/tonysmdev/'
      icon: site/social-icons/twitter.svg
    -
      name: Github
      url: 'https://github.com/tonysm/'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: 'mailto:tonysm@hey.com'
      icon: site/social-icons/email.svg
